export default async function handler(req, res) {
  const { username } = req.query;
  
  try {
    // In a real implementation, you would fetch the actual contribution data
    // GitHub doesn't have an official API for contribution data, so you might need to:
    // 1. Use GitHub GraphQL API to fetch contribution data (requires authentication)
    // 2. Or parse the SVG generated by the GitHub Actions workflow

    // Placeholder response with mock data
    res.status(200).json({
      username,
      contributionGrid: [
        // Mock contribution data - you'd replace this with real data
        [0, 1, 2, 0, 3, 0, 0],
        [0, 0, 1, 0, 2, 0, 1],
        [0, 0, 0, 3, 0, 1, 0],
        [0, 2, 0, 0, 0, 0, 0],
        [1, 0, 0, 4, 2, 0, 0],
      ]
    });
  } catch (error) {
    console.error('Error fetching contribution data:', error);
    res.status(500).json({ error: 'Failed to fetch contribution data' });
  }
}